### PR TITLE
fix: always rollback

### LINKED ISSUE #637: Rollback is not called if there is a panic
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Current use of `BeginTx`, `CommitTx` and `RollbackTx` in Fosite is problematic because it does not call `RollbackTx` when panic happens. We could assume that Fosite itself does not panic, but that is not necessary true for code it calls into. For example, I had a bug inside my storage implementation which triggered panic. As the panic propagated and was handled higher up in my request handler and logged, transaction itself was not rolled back, leaving the connection over it in an inconsistent state. With connection pooling that brought some stability issues.

### Reproducing the bug

Sadly I do not have a simple reproduction here. One which I was able to do is with Sqlite and setting `SetMaxOpenConns` to 1. Then if a transaction is not rolled back, no other operation can be done on the database and my code hangs. This is how I am now testing that all transactions are properly rolled back.

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

observed on current master branch

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mitar**
## Related Issue or Design Document

Fixes #637.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

There is not much change necessary to get this fixed. See the diff.

There is one logical change I have done: before rollback was not called if commit failed, now I made it that it is called if commit fails. It is generally safe to call rollback outside of a transaction in PostgreSQL (you only get warning), but if the connection is in error state, then rollback is required. So just to be safe, I think it is better to rollback on any error, including when commit fails (because we might not know what is the reason for failure of that call and in what state is the connection).

### CODE REVIEW

File: handler/oauth2/flow_authorize_code_token.go [hunk 1]
```diff
@@ -170,22 +170,20 @@ func (c *AuthorizeExplicitGrantHandler) PopulateTokenEndpointResponse(ctx contex
...
-	if err := c.CoreStorage.InvalidateAuthorizeCodeSession(ctx, signature); err != nil {
-		if rollBackTxnErr := storage.MaybeRollbackTx(ctx, c.CoreStorage); rollBackTxnErr != nil {
-			return errorsx.WithStack(fosite.ErrServerError.WithWrap(err).WithDebugf("error: %s; rollback error: %s", err, rollBackTxnErr))
+	defer func() {
+		if err != nil {
+			if rollBackTxnErr := storage.MaybeRollbackTx(ctx, c.CoreStorage); rollBackTxnErr != nil {
+				err = errorsx.WithStack(fosite.ErrServerError.WithWrap(err).WithDebugf("error: %s; rollback error: %s", err, rollBackTxnErr))
+			}
 		}
+	}()
```
Comment (aeneasr) [inline handler/oauth2/flow_authorize_code_token.go:179]: This wouldn't roll back on a panic, it rewires the logic from explicit rollback to implicit via defer. A panic would need a recover on the top level: https://go.dev/blog/defer-panic-and-recover

Comment (mitar) [reply handler/oauth2/flow_authorize_code_token.go:179]: Of course it would. From the link you posted itself (emphasis mine):

> Panic is a built-in function that stops the ordinary flow of control and begins panicking. When the function F calls panic, execution of F stops, **any deferred functions in F are executed normally**, and then F returns to its caller. To the caller, F then behaves like a call to panic. The process continues up the stack until all functions in the current goroutine have returned, at which point the program crashes.

Comment (aeneasr) [reply handler/oauth2/flow_authorize_code_token.go:179]: In German we say: "Wer lesen kann ist klar im Vorteil" (loosely translated to "Who can read has a clear advantage"). You're absolutely right, this does indeed catch any panic happening!

File: handler/oauth2/flow_authorize_code_token.go [hunk 2]
```diff
@@ -198,7 +196,7 @@ func (c *AuthorizeExplicitGrantHandler) PopulateTokenEndpointResponse(ctx contex
 		responder.SetExtra("refresh_token", refresh)
 	}
 
-	if err := storage.MaybeCommitTx(ctx, c.CoreStorage); err != nil {
+	if err = storage.MaybeCommitTx(ctx, c.CoreStorage); err != nil {
```
Comment (aeneasr) [inline handler/oauth2/flow_authorize_code_token.go:199]: One problem I have observed with this control flow is that RDBMS roll back transactions automatically when commits fail. When rolling back a failed transaction, we will always end up with an error because there is nothing to roll back any more. This in turn causes the root of the issue (e.g. duplicate key) to be quite difficult to find/debug, because it is hidden in the rollback error and is probably missing content.

We had this issue in Hydra, the fix is to just return commit errors normally.

File: handler/oauth2/flow_authorize_code_token.go (hunk 1 above)
Comment (mitar) [reply handler/oauth2/flow_authorize_code_token.go:179]: :-)

File: handler/oauth2/flow_authorize_code_token.go (hunk 2 above)
Comment (mitar) [reply handler/oauth2/flow_authorize_code_token.go:199]: > One problem I have observed with this control flow is that RDBMS roll back transactions automatically when commits fail.

Yes, I note this (and rationale for this change) in the description of the PR:

> There is one logical change I have done: before rollback was not called if commit failed, now I made it that it is called if commit fails. It is generally safe to call rollback outside of a transaction in PostgreSQL (you only get warning), but if the connection is in error state, then rollback is required. So just to be safe, I think it is better to rollback on any error, including when commit fails (because we might not know what is the reason for failure of that call and in what state is the connection).

> When rolling back a failed transaction, we will always end up with an error because there is nothing to roll back any more.

Hm, at least in [PostgreSQL you do not get an error](https://www.postgresql.org/docs/devel/sql-rollback.html):

> Issuing `ROLLBACK` outside of a transaction block emits a warning and otherwise has no effect.

With which database have you noticed the error?

> This in turn causes the root of the issue (e.g. duplicate key) to be quite difficult to find/debug, because it is hidden in the rollback error and is probably missing context.

I think this can be fixed a bit. So regular error looks like:

`errorsx.WithStack(fosite.ErrServerError.WithWrap(storageErr).WithDebug(storageErr.Error()))`

Current rollback error hides the regular error completely:

`err = errorsx.WithStack(fosite.ErrServerError.WithWrap(rbErr).WithDebug(rbErr.Error()))`

But in `PopulateTokenEndpointResponse` we have in fact a precedence which I think addresses the issue:

`errorsx.WithStack(fosite.ErrServerError.WithWrap(err).WithDebugf("error: %s; rollback error: %s", err, rollBackTxnErr))`

I think I could adopt this for rollback error everywhere. So:

`errorsx.WithStack(fosite.ErrServerError.WithWrap(storageErr).WithDebugf("error: %s; rollback error: %s", storageErr, rbErr))`

Comment (aeneasr) [reply handler/oauth2/flow_authorize_code_token.go:199]: > With which database have you noticed the error?

I don't quite remember, I think it was either MySQL or CockroachDB :/

> I think I could adopt this for rollback error everywhere. So:

SGTM! :)

**Comment by aeneasr** [comment]
Are you still up for the changes? :monocle_face: If you need any help, let us know!

I'll convert this to a draft in the meanwhile. When it's ready for review again, please remove the draft indicator! 👀

**Comment by mitar** [comment]
Yes yes. I was just a bit busy with other things.

**Comment by aeneasr** [comment]
All good. I think I am known by now as one of the slowest maintainers in open source 😓

File: handler/oauth2/flow_authorize_code_token.go (hunk 2 above)
Comment (mitar) [reply handler/oauth2/flow_authorize_code_token.go:199]: Done.

**Comment by mitar** [comment]
> All good. I think I am known by now as one of the slowest maintainers in open source

What? No way. You are one of best maintainers I have seen around. Regularly checking in, always giving great feedback, pushing PRs through and not leaving them stick around.

**Comment by aeneasr** [comment]
> What? No way. You are one of best maintainers I have seen around. Regularly checking in, always giving great feedback, pushing PRs through and not leaving them stick around.

You made my day, thank you :)

**Comment by mitar** [comment]
BTW, those tests are failing also in `master` branch.

**Comment by mitar** [comment]
ping @aeneasr

**Comment by aeneasr** [comment]
Ah yes it fails because the refresh PR has not yet been merged. I'd like for the OIDC conformity siute to pass first so that we can confirm that the rollback has no unintended effects :)

**Comment by mitar** [comment]
Which other PR?

**Comment by aeneasr** [comment]
i merged a workaround, let's see if we're green!
