### PR TITLE
fix: only use allowed characters in error_description

### LINKED ISSUE #525: Non-conformant error responses
**Describe the bug**

We recently changed the way `error_description` and other error fields are generated. This unfortunately caused two warnings and one failure in the OpenID Connect Conformity Test Suite, specifically the  `oidcc-response-type-missing` test.

**To Reproduce**

The full test log can be seen here: [test-log-oidcc-response-type-missing-client_secret_basic-discovery-code-default-dynamic_client-8XprPDGkiQ09O8v.zip](https://github.com/ory/fosite/files/5486535/test-log-oidcc-response-type-missing-client_secret_basic-discovery-code-default-dynamic_client-8XprPDGkiQ09O8v.zip)

**WARNING: `error_hint` is unexpected**

*I think this can be ignored*

> error response includes unexpected parameters. This may be because the server supports extensions the test suite is unaware of, or the server may be returning values it should not.

**WARNING: `error_hint` is unexpected**

*I think this can be ignored*

> error response includes unexpected parameters. This may be because the server supports extensions the test suite is unaware of, or the server may be returning values it should not.

**WARNING error_description has CR LF or TAB**

*This should be fixed*

> 'error_description' field includes characters CR, LF or TAB, these are not recommended to include
>
> * see: https://bitbucket.org/openid/connect/issues/1147/certification-rfc6749-must-for
> * error_description: The authorization server does not support obtaining a token using this method The request is missing the "response_type"" parameter.

**ERROR invalid characters in error_description**

> 'error_description' field MUST NOT include characters outside the set %09-0A (Tab and LF) / %x0D (CR) / %x20-21 / %x23-5B / %x5D-7E
> * error_description: The authorization server does not support obtaining a token using this method The request is missing the "response_type"" parameter.

**Expected behavior**

The test should pass.

**Environment**

ORY Fosite `v0.34.1`

**Additional context**

Bildschirmfoto 2020-11-04 um 09 49 20

/cc @mitar could you take a look maybe?

### PR DESCRIPTION
**Pull request by aeneasr**
Replace LF and quotes with `.` and `'` to match allowed and recommended character set defined in various RFCs.

Closes #525

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

### CODE REVIEW

File: audience_strategy.go [hunk 1]
```diff
@@ -18,14 +18,14 @@ func DefaultAudienceMatchingStrategy(haystack []string, needle []string) error {
 	for _, n := range needle {
 		nu, err := url.Parse(n)
 		if err != nil {
-			return errors.WithStack(ErrInvalidRequest.WithHintf(`Unable to parse requested audience "%s".`, n).WithCause(err).WithDebug(err.Error()))
+			return errors.WithStack(ErrInvalidRequest.WithHintf("Unable to parse requested audience '%s'.", n).WithCause(err).WithDebug(err.Error()))
```
Comment (mitar) [inline audience_strategy.go:21]: What if audience contains `"` for some reason?

I think we should also sanitize manually final error description before we output it out.

File: authorize_request_handler.go [hunk 2]
```diff
@@ -104,23 +109,23 @@ func (f *Fosite) authorizeRequestParametersFromOpenIDConnectRequest(request *Aut
 		case *jwt.SigningMethodRSA:
 			key, err := f.findClientPublicJWK(oidcClient, t, true)
 			if err != nil {
-				return nil, errors.WithStack(ErrInvalidRequestObject.WithHint("Unable to retrieve RSA signing key from OAuth 2.0 Client.").WithCause(err).WithDebug(err.Error()))
+				return nil, errors.WithStack(ErrInvalidRequestObject.WithHintf("Unable to retrieve RSA signing key from OAuth 2.0 Client because: %s.", err).WithCause(err).WithDebug(err.Error()))
```
Comment (mitar) [inline authorize_request_handler.go:112]: No, we should never leak `err` out, just when debugging. I removed this recently in one PR. So `because ...` bit I worry about. (Especially if we will implement custom key search strategies with https://github.com/ory/fosite/issues/452)

File: client_authentication_jwks_strategy.go [hunk 3]
```diff
@@ -60,17 +60,17 @@ func (s *DefaultJWKSFetcherStrategy) Resolve(location string, forceRefresh bool)
 	if !ok || forceRefresh {
 		response, err := s.client.Get(location)
 		if err != nil {
-			return nil, errors.WithStack(ErrServerError.WithHintf(`Unable to fetch JSON Web Keys from location "%s".`, location).WithCause(err).WithDebug(err.Error()))
+			return nil, errors.WithStack(ErrServerError.WithHintf("Unable to fetch JSON Web Keys from location '%s' because: %s.", location, err).WithCause(err).WithDebug(err.Error()))
```
Comment (mitar) [inline client_authentication_jwks_strategy.go:63]: Same here. `err` could be sensitive.

File: client_authentication_jwks_strategy.go [hunk 4]
```diff
@@ -60,17 +60,17 @@ func (s *DefaultJWKSFetcherStrategy) Resolve(location string, forceRefresh bool)
...
 
 		if response.StatusCode < 200 || response.StatusCode >= 400 {
-			return nil, errors.WithStack(ErrServerError.WithHintf(`Expected successful status code from location "%s", but received code "%d".`, location, response.StatusCode))
+			return nil, errors.WithStack(ErrServerError.WithHintf("Expected successful status code from location '%s' but received code %d.", location, response.StatusCode))
 		}
 
 		var set jose.JSONWebKeySet
 		if err := json.NewDecoder(response.Body).Decode(&set); err != nil {
-			return nil, errors.WithStack(ErrServerError.WithHintf("Unable to decode JSON Web Keys from location \"%s\".", location).WithCause(err).WithDebug(err.Error()))
+			return nil, errors.WithStack(ErrServerError.WithHintf("Unable to decode JSON Web Keys from location '%s' because: %s.", location, err).WithCause(err).WithDebug(err.Error()))
```
Comment (mitar) [inline client_authentication_jwks_strategy.go:73]: And here.

File: errors.go [hunk 5]
```diff
@@ -339,12 +340,12 @@ func (e *RFC6749Error) Sanitize() *RFC6749Error {
...
 	if e.Hint != "" {
-		description += "\n\n" + e.Hint
+		description += " " + e.Hint
 	}
 	if e.Debug != "" {
-		description += "\n\n" + e.Debug
+		description += " " + e.Debug
 	}
-	return description
+	return strings.ReplaceAll(description, "\"", "'")
```
Comment (mitar) [inline errors.go:348]: Also `\` is not allowed, and anything non-ASCII, so I think we have to sanitize this more.

File: authorize_request_handler.go (hunk 2 above)
Comment (aeneasr) [reply authorize_request_handler.go:112]: Hm I see your point but the problem is that this is really hard to debug. You would have to turn on debug mode for clients to understand why their request failed (e.g. `kid` does not exist, wrong alg, ...). So we need a way to return the appropriate error to the regular OAuth2 consumer without enabling debug.

File: errors.go (hunk 5 above)
Comment (aeneasr) [reply errors.go:348]: Right, my idea here was to just remove this for any stray characters but I guess we could santize it even more - but would probably mark this as a feature instead of addressing this here.

File: audience_strategy.go (hunk 1 above)
Comment (aeneasr) [reply audience_strategy.go:21]: https://github.com/ory/fosite/issues/527

File: errors.go (hunk 5 above)
Comment (aeneasr) [reply errors.go:348]: https://github.com/ory/fosite/issues/527

File: client_authentication_jwks_strategy.go (hunk 3 above)
Comment (aeneasr) [reply client_authentication_jwks_strategy.go:63]: Hm I don't really think that's the case. `net/http` is basically just saying DIAL errors on hostnames and IPs. Since the location is given by the client anyways I don't think there's much that could leak here?

Comment (aeneasr) [reply client_authentication_jwks_strategy.go:63]: But yeah scrap my last comment - you're right. I've addressed this!

File: authorize_request_handler.go (hunk 2 above)
Comment (mitar) [reply authorize_request_handler.go]: I think we should then check for known error messages and map it? Like [it is done here](https://github.com/ory/fosite/blob/master/handler/oauth2/strategy_jwt.go#L108-L134) already?
